spring:
  profiles:
    active: dev1
  application:
    name: upms-service
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.address}
        username: ${nacos.user}
        password: ${nacos.password}
        namespace: ${nacos.namespace}

server:
  port: 6001
