spring:
  application:
    name: work-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.address}
        username: ${nacos.user}
        password: ${nacos.password}
        namespace: ${nacos.namespace}
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        - id: upms-service
          uri: lb://upms-service
          predicates:
            - Path=/api/upms/**
#feign:
#  hystrix:
#    enabled: true
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000
#  threadpool:
#    default:
#      coreSize: 5 #并发执行的最大线程数，默认10
#      maxQueueSize: 10 #BlockingQueue的最大队列数，默认值-1
#      queueSizeRejectionThreshold: 5 #即便maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝，默认值5
server:
  port: 6060
